# Generated by Django 4.2.3 on 2023-07-24 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('fullname', models.CharField(max_length=250, verbose_name='fullname')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('client', models.ManyToManyField(to='newsletters.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('frequency', models.CharField(max_length=50, verbose_name='frequency')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(default='created', max_length=100, verbose_name='status')),
                ('response', models.CharField(blank=True, max_length=250, null=True, verbose_name='response')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.content', verbose_name='content')),
            ],
            options={
                'verbose_name': 'trials',
                'verbose_name_plural': 'trials',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.newsletter', verbose_name='settings'),
        ),
    ]
