# Generated by Django 4.2.2 on 2023-07-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['date'], 'verbose_name': 'trial', 'verbose_name_plural': 'trials'},
        ),
        migrations.AddField(
            model_name='trial',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletters.client', verbose_name='client'),
            preserve_default=False,
        ),
    ]
