# Generated by Django 4.2.3 on 2023-07-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_client_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['time'], 'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
    ]
