# Generated by Django 4.2.3 on 2023-07-24 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
