# Generated by Django 4.2.3 on 2023-07-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_client_owner_newsletter_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['time'], 'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
    ]
