# Generated by Django 4.2.3 on 2023-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='status'),
        ),
    ]
